version: '3'

services:
  postgres:
    container_name: postgres_authg
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: authg
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres-db:
    driver: local